Repository osamhack2022/WEB_AI_MILIROUTINE_MILIROUTINE, pull requests merged in 2022-10, with the labels that each got.

#9 Header 컴포넌트 작성
  WEB(FE)/package.json
  WEB(FE)/postcss.config.cjs
  WEB(FE)/src/assets/Logo.png
  WEB(FE)/src/components/Element/Button.tsx
  WEB(FE)/src/components/Element/Header.tsx
  WEB(FE)/src/components/Element/NavItem.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/tailwind.config.cjs
  WEB(FE)/tailwind.config.js
  WEB(FE)/yarn.lock
Labels: feature, FE

#13 Footer 컴포넌트
  WEB(FE)/src/App.css
  WEB(FE)/src/components/Element/Footer.tsx
  WEB(FE)/src/components/Element/Header.tsx
  WEB(FE)/src/components/Element/Jumbotron.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/src/index.css
  WEB(FE)/src/routes/index.tsx
  WEB(FE)/tailwind.config.cjs
Labels: feature, FE

#5 로그인, 회원가입, 로그아웃 기능 구현
  WEB(BE)/src/controllers/home.ctrl.js
  WEB(BE)/src/controllers/login.ctrl.js
  WEB(BE)/src/controllers/logout.ctrl.js
  WEB(BE)/src/controllers/signup.ctrl.js
  WEB(BE)/src/db/.env
  WEB(BE)/src/models/index.js
  WEB(BE)/src/routes/index.js
  WEB(BE)/src/routes/login.js
  WEB(BE)/src/routes/logout.js
  WEB(BE)/src/routes/signup.js
  WEB(BE)/src/views/index.ejs
  WEB(BE)/src/views/signmore.ejs
  WEB(BE)/src/views/signup.ejs
  goorm.manifest
Labels: feature, BE

#16 MiliRoutine Item Component
  WEB(FE)/src/components/Element/RoutineItem.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/tailwind.config.cjs
Labels: feature, FE

#20 Slider 컴포넌트
  WEB(FE)/package.json
  WEB(FE)/src/components/Element/Carousel.tsx
  WEB(FE)/src/components/Element/RoutineItem.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/tailwind.config.cjs
  WEB(FE)/yarn.lock
Labels: feature, FE

#24 React Router 페이지 분기 처리
  WEB(FE)/src/features/auth/routes/Login.tsx
  WEB(FE)/src/features/auth/routes/Signup.tsx
  WEB(FE)/src/features/auth/routes/index.tsx
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/src/features/misc/routes/Popular.tsx
  WEB(FE)/src/features/misc/routes/index.tsx
  WEB(FE)/src/features/my/index.ts
  WEB(FE)/src/features/my/routes/MyPage.tsx
  WEB(FE)/src/features/my/routes/MyRoutineAuth.tsx
  WEB(FE)/src/features/my/routes/PointShop.tsx
  WEB(FE)/src/features/my/routes/Setting.tsx
  WEB(FE)/src/features/my/routes/index.tsx
  WEB(FE)/src/features/routine/RoutineDetail.tsx
  WEB(FE)/src/features/routine/RoutineMake.tsx
  WEB(FE)/src/features/routine/index.tsx
  WEB(FE)/src/routes/index.tsx
  WEB(FE)/src/routes/protected.tsx
Labels: feature, FE

#33 회원가입
  WEB(FE)/src/components/Element/Button.tsx
  WEB(FE)/src/components/Element/Form.tsx
  WEB(FE)/src/components/Element/Header.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/components/Layout/AuthLayout.tsx
  WEB(FE)/src/components/Layout/MainLayout.tsx
  WEB(FE)/src/components/Layout/index.ts
  WEB(FE)/src/features/auth/routes/Signup.tsx
  WEB(FE)/src/routes/index.tsx
  WEB(FE)/src/routes/public.tsx
  WEB(FE)/tailwind.config.cjs
Labels: feature, FE

#36 루틴 생성 페이지 1
  WEB(FE)/src/components/Element/Dropdown.tsx
  WEB(FE)/src/components/Element/Header.tsx
  WEB(FE)/src/components/Element/NavItem.tsx
  WEB(FE)/src/components/Element/Select.tsx
  WEB(FE)/src/components/Element/index.ts
  WEB(FE)/src/features/misc/routes/Landing.tsx
  WEB(FE)/src/features/routine/RoutineMake.tsx
  WEB(FE)/src/routes/index.tsx
Labels: FE

#31 Fit FE : controllers 파일들 수정
  WEB(BE)/.gitignore
  WEB(BE)/src/controllers/home.ctrl.js
  WEB(BE)/src/controllers/login.ctrl.js
  WEB(BE)/src/controllers/logout.ctrl.js
  WEB(BE)/src/controllers/routine.ctrl.js
  WEB(BE)/src/controllers/signup.ctrl.js
  WEB(BE)/src/controllers/user.ctrl.js
  WEB(BE)/src/db/config.js
  WEB(BE)/src/models/index.js
  WEB(BE)/src/routes/index.js
  WEB(BE)/src/routes/login.js
  WEB(BE)/src/routes/routine.js
  WEB(BE)/src/routes/signup.js
  WEB(BE)/src/routes/user.js
  WEB(BE)/src/routes/user/my.js
  WEB(BE)/src/token/jwt.js
  WEB(BE)/src/views/MakingRoutine.ejs
  WEB(BE)/src/views/alert.ejs
  WEB(BE)/src/views/index.ejs
  WEB(BE)/src/views/login.ejs
  WEB(BE)/src/views/signmore.ejs
  WEB(BE)/src/views/signup.ejs
Labels: BE
